project_id = "akbmcsjeityrozgsibng"

[functions.chat-ai]
verify_jwt = false

[functions.generate-avatar]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false

[functions.speech-to-text]
verify_jwt = false

[functions.create-elevenlabs-agent]
verify_jwt = false

[functions.get-elevenlabs-url]
verify_jwt = false

[functions.bulk-create-catbots]
verify_jwt = false