project_id = "akbmcsjeityrozgsibng"

[functions.chat-ai]
verify_jwt = false

[functions.generate-avatar]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false

[functions.speech-to-text]
verify_jwt = false