export const PREDEFINED_TAGS = [
  'Fantasy',
  'Sci-Fi',
  'Gaming',
  'Anime',
  'Movies',
  'Books',
  'RPG',
  'Religion',
  'Creative Writing',
  'Business',
  'Teacher',
  'Expert',
  'Coach',
  'Therapist',
  'Manga',
  'Travel',
  'LGBTQ+',
  'Music',
  'Art',
  'Sports',
  'Nature',
  'Technology',
  'History',
  'Politics',
  'Philosophy',
  'Educational',
  'Cooking',
  'Companion',
  'Text Adventure',
  'Friend',
  'Spirituality'
] as const;

export type PredefinedTag = typeof PREDEFINED_TAGS[number];
