// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://akbmcsjeityrozgsibng.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFrYm1jc2plaXR5cm96Z3NpYm5nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MTY1NDYsImV4cCI6MjA3Mjk5MjU0Nn0.p77zO8q7hlp8KyGdn0vb1VuvU9VQu_CZY9_4GphlXBA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});